### ISSUE TITLE
Windows linking error with fmt 11.1.* and spdlog built with 11.0.*

### ISSUE THREAD

**Issue by ryanvolz** [conda-forge/fmt-feedstock#61]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

I got the following linking error on Windows when [building gnuradio](https://github.com/conda-forge/gnuradio-feedstock/pull/292) with the latest fmt 11.1.4 release:
```
2025-03-06T23:19:54.4113464Z logger.cc.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl spdlog::pattern_formatter::format(struct spdlog::details::log_msg const &,class fmt::v11::basic_memory_buffer<char,250,struct fmt::v11::detail::allocator<char> > &)" (?format@pattern_formatter@spdlog@@UEAAXAEBUlog_msg@details@2@AEAV?$basic_memory_buffer@D$0PK@U?$allocator@D@detail@v11@fmt@@@v11@fmt@@@Z)
2025-03-06T23:19:54.4116011Z 
2025-03-06T23:19:54.4116776Z gnuradio-runtime\lib\gnuradio-runtime.dll : fatal error LNK1120: 1 unresolved externals
```

After some digging, this stems from the following change in fmt that went into the 11.1 series: https://github.com/fmtlib/fmt/commit/c0fab5e2f7c40234c14960873717fb5760fde1fd. It changes the default allocator for the `basic_memory_buffer` class. Since the latest spdlog package on conda-forge was built against fmt 11.0 and uses `basic_memory_buffer` with the default allocator, building against spdlog and fmt 11.1 causes the above linking error since the spdlog library does not have a definition with the new default allocator from fmt 11.1.

For gnuradio, I forced a build with fmt 11.0 which succeeded and seems to be able to run with the fmt 11.1.4 library installed, but perhaps my quick test failed to exercise the offending class. I suppose once spdlog is built against fmt 11.1 and gets installed in an environment where gnuradio was built with the older spdlog and fmt 11.0, then runtime errors might start happening.

### Installed packages

```shell
fmt:                       11.1.4-hf4da5c8_0                conda-forge
spdlog:                    1.15.1-hf4138ee_0                conda-forge
```

### Environment info

```shell
CI, N/A
```

**Comment by SylvainCorlay** [comment]
Should fmt 11.1.x should be marked as broken, or should we make spdlog pin fmt<11.1 in a repodata patch?

**Comment by ryanvolz** [comment]
> Should fmt 11.1.x should be marked as broken, or should we make spdlog pin fmt<11.1 in a repodata patch?

I guess it depends on whether the @conda-forge/fmt maintainers want to pull the fmt 11.1.x releases and patch the ABI breakage or keep them and try to repodata patch and change the global pinning so that 11.0 and 11.1 are recognized as separate ABIs. Typing that out, the first option sounds a lot easier.

**Comment by jjerphan** [comment]
conda-forge could distribute fmt with a patch reverting [the commit which introduces the breaking change](https://github.com/fmtlib/fmt/commit/c0fab5e2f7c40234c14960873717fb5760fde1fd): nothing but a change of a default allocator would be lost, and forward- and backward-compatibility on major versions would be maintained — on conda-forge, most DSO/binaries (including fmt's) depend on the C++ standard libraries' runtime anyway (making the intent of the aforementioned commit unrealizable for now at least).

What do you think of it?

**Comment by thraneh** [comment]
Perhaps being stuck with with fmt 11.0.2 is going to cause issues with clang 20.1.1 which has now be made available on conda-forge.

* https://github.com/fmtlib/fmt/issues/4396

I have now tried to install fmt using `conda install -c conda-forge/label/broken 'fmt==11.1.4'` and the issue indeed seems to be resolved with a more recent version of fmt.

**Comment by jjerphan** [comment]
FYI, people only have been observed this issue producing a fatal error on Windows.

**Comment by saraedum** [comment]
> change the global pinning so that 11.0 and 11.1 are recognized as separate ABIs

Since fmt has a history of breaking ABI changes, maybe it makes sense to pin with x.x going forward. What's the problem with such a repodata patch (other than it being more work?)

**Comment by h-vetinari** [comment]
> Since fmt has a history of breaking ABI changes

I think fmt makes a big effort _not_ to break ABI, but it can still happen despite that. Case-in-point: upstream is [considering](https://github.com/fmtlib/fmt/issues/4385) to fix the unintentional ABI break, because we asked.

> maybe it makes sense to pin with x.x going forward

Given how painful and long-running fmt migrations are, I'd want to avoid doing this for minor versions... Otherwise we get even more conflicts between X.Y and X.{Y+1} than we're already getting between X&Y. I agree it's not 100% clear-cut given the fallout when things do break, but for now I'm counting upstream's willing to rapidly fix breakage as "effectively ABI-stable".

In any case, we were asked to test https://github.com/fmtlib/fmt/commit/784eac839df77df1852dc1c50b17b76c3aec8f4a, which I've pushed to a separate branch behind a `fmt_dev` label. I'd be grateful if affected feedstocks can test this out by adding
```yaml
channel_sources:
  - conda-forge,conda-forge/label/fmt_dev
```
to `recipe/conda_build_config.yaml` and then rerendering.

**Comment by h-vetinari** [comment]
Actually #63 already ended up publishing new 11.1.x builds to the main label, so we probably need to either mark those as broken too, or move fast here.

**Comment by thraneh** [comment]
> Actually [#63](https://github.com/conda-forge/fmt-feedstock/pull/63) already ended up publishing new 11.1.x builds to the main label, so we probably need to either mark those as broken too, or move fast here.

For what it's worth, fmt 11.1.4 (main) compiles fine (for my use-cases) with clang 20.1.1 (main) on OSX.

I didn't have a break as such, but I was stuck with clang 19.1.x.

I find that it's challenging when you publish a package to main and later mark it "broken". Then it can happen that a downstream package, possibly packaged outside conda-forge, was built with a dependency that can no longer be downloaded. This could cause slightly different kind of "brokenness" than the ABI stability that has been discussed in this thread. I understand that there are no good solutions for this problem and just giving some feedback from my perspective.

**Comment by h-vetinari** [comment]
So I tested this in https://github.com/conda-forge/gnuradio-feedstock/pull/295, and it seems that the upstream revert was not enough to fix this. At this point, I think we should call it as "well, we tried", and move on to a minor pin, at least for 11.x. I'd like to retry the major pin for 12.x though. 🤞

**Comment by ryanvolz** [comment]
I think this particular issue has been satisfactorily addressed by tightening the pin.

> So I tested this in [conda-forge/gnuradio-feedstock#295](https://github.com/conda-forge/gnuradio-feedstock/pull/295), and it seems that the upstream revert was not enough to fix this. At this point, I think we should call it as "well, we tried", and move on to a minor pin, at least for 11.x. I'd like to retry the major pin for 12.x though. 🤞

It might have worked actually, but I think `gnuradio` is now running into [a different bug on Windows](https://github.com/conda-forge/gnuradio-feedstock/pull/296#issuecomment-2766618150) that stems from another change in fmt 11.1. I haven't figured this one out yet, but my guess is that it is related to `native_formatter<T, Char, TYPE>::format` no longer being exported: https://github.com/fmtlib/fmt/pull/3991/files#r1627984786. That should be a separate issue, so I'll follow up elsewhere when I get a little more clarity.
